### ISSUE TITLE
[Q] Since SyntaxError is also built-in, how do you usually handle that?

### ISSUE THREAD

**Issue by erapoport** [shutterstock/node-common-errors#14]
I fully expect that as soon as I start using this library, someone will get confused between `SyntaxError` and `errors.SyntaxError`.

I just wrote this test and it doesn't pass:

     expect(err).to.be.an.instanceOf(errors.SyntaxError);

It does pass if I say `instanceOf(SyntaxError)`. How can I globally overwrite the default one to keep the code sanity?

Thank you!

**Comment by dfenster** [comment]
The standard error classes are re-included in common-errors in order to allow you to append stack traces

```
new errors.SyntaxError("no exclamation point allowed", someOtherError)
```

If you ever want to know if something is a SyntaxError, use instanceof(SyntaxError) with the global class as it will work for both.

I was a little wary of replacing the standard error classes with common-errors globally because of unintended side-effects. If that works for you, feel free to do so.

**Comment by Madd0g** [comment]
`instanceOf(SyntaxError)` would work for both if I pass the original SyntaxError error? 

     //bluebird typed error catcher
     .catch(SyntaxError, (e) => throw new errors.SyntaxError(no exclamation point allowed", e))

Have I read that correctly?

**Comment by erapoport** [comment]
`instanceOf(SyntaxError)` would work for both if I pass the original SyntaxError error? 

     //bluebird typed error catcher
     .catch(SyntaxError, (e) => throw new errors.SyntaxError(no exclamation point allowed", e))

Have I read that correctly?

**Comment by dfenster** [comment]
Yep!

If that does not work I consider it to be a bug that I will patch asap. I have tests that tell me it works, but do please let me know if you find differently.

**Comment by Madd0g** [comment]
Weird, I thought that was exactly what I was doing. I'll try to find what I'm doing wrong, thanks!

**Comment by Madd0g** [comment]
Wonderful, it was indeed my mistake and now both types pass the test.  Now that part is working, but `err.toString()`seems to contain only the message from when I rethrow the error, not them both glued together as I expected.

**Comment by erapoport** [comment]
Wonderful, it was indeed my mistake and now both types pass the test.  Now that part is working, but `err.toString()`seems to contain only the message from when I rethrow the error, not them both glued together as I expected.
