### ISSUE TITLE
Make `new` optional?

### ISSUE THREAD

**Issue by diversario** [shutterstock/node-common-errors#16]
What if every error took care of ensuring that `new` is called even if user instantiates it without one? The usual way of doing that is something like

```javascript
function Foo() {
  if (!(this instanceof Foo)) {
    return new Foo() // pass arguments here, of course
  }
}
```

I think it could save some time for users who, like me, forget to use `new` on `errors.Error` etc. and spend time trying to figure out what's wrong.

**Comment by dfenster** [comment]
I'm not personally a big fan of no "new" keyword, but it does seem to be popular these days. Regardless, the Error class in V8 works without the "new" keyword, and I therefore believe this library should as well.
I'll add it. Thanks.

**Comment by dfenster** [comment]
Complete
