### ISSUE TITLE
Append extra data to errors

### ISSUE THREAD

**Issue by thefabulousdev** [shutterstock/node-common-errors#17]
Is it possible to append extra data to the errors? My particular interest is on the custom ones.

e,g,

```js
var TokenModelNotFoundError = helpers.generateClass('TokenModelNotFoundError', {
    extends: errors.NotFoundError,
    args: ['modelName','tokenName'],
    generateMessage: function(){
        return sprintf('The %s model from the given %s token was not found',this.modelName,this.tokenName);
    },
    someExtraData : {
        journey : function(){
            // Do something, perhaps with the arguments given
            return someObject;
        }
    }
});
```
and have it on the generated JSON
```js
{
    // ...
    someExtraData : {
        journey : { // The generated object }
    }
}
```

**Comment by dfenster** [comment]
One thing you could do is add your own "toJSON" method on the class that you get as a result of the generateClass method. Then, when you call JSON.stringify, it will use that method to know what the output should be.

Did you have a different idea, or a suggestion on what you would like the library to do? Is there some value here that I can add that would benefit you and others?
