### ISSUE TITLE
Shutterstock user credentials must be included on the client?

### ISSUE THREAD

**Issue by misterfresh** [shutterstock/node-common-errors#23]
Example in 
https://github.com/shutterstock/api/blob/master/examples/javascript-jquery/v2.html
seems to require to include the clientId and the clientSecret on the client, in order to use the api.

Is there a way to include a temporary token instead? What is the recommended approach to use shutterstock api directly from the browser?

**Comment by dfenster** [comment]
Hi, I think you might have opened this ticket in the wrong repository.
It can be ok to include the client secret on the client so long as you realize that anyone can masquerade as your app when they use the Shutterstock API from their own app.

To avoid such a weakness, you might want to have your web server store the client id and secret, and proxy all API calls through your web server over HTTPS. You could store the user's access token as a secure-only and HTTP-only cookie.

**Comment by misterfresh** [comment]
I wanted to open it in the shutterstock/api repo but the option was not available. Anyway I did the proxy method and it works, thanks!
